"""Embedded click sample for the analysis progress ticker.

The sound is baked into this module as XOR-scrambled, base64-encoded
raw float32 PCM. It is never written to disk and, because of the
scrambling, cannot be played without going through ``load_click_pcm()``
first. That keeps the ticker sound a tiny bit mysterious and avoids
leaving a WAV file in the user's temp directory.

Do not edit by hand — regenerated by ``scripts/generate_click.py``
(see project root) when the ticker sound is to be changed.
"""

from __future__ import annotations

import base64

SAMPLE_RATE = 44100
SAMPLE_COUNT = 1323

_KEY = bytes.fromhex("5ac38f21e74b921d")

_DATA_B64 = (
    "WsOPIcZp86RTX0Md5q9DIT6ZgRpAXqwgz7YeHMtL4CBaDWcczmQuIX/mKJ3aN7Ug76AdHcJOB6BF"
    "FU6cyzk6o5I7gZ9fa1ygC5VxnAND/6BhvkOc8dV+Idk1FZ0HZG8g53rHH4/sFCMQggofos6fIkbo"
    "TR/fY9wj5kOTH8Qba6Bri+wcx7DeISI85Z+/ZjOjbsplnVTpPaPGCCafe/27olc3/p83Wa2i7Y7L"
    "n3rGGaB+I4QfDXyCoxDskh/DUL0ipDSEHszbziIqQSIfyaGUIztzMh/3eb4gp2XFHznDgCNubp6a"
    "t3CAIB1yqJ4kD4qjRIkqn8OwMqMYkkqfFei2oqyIAJ8XqpijQIMDnwbaESMyj5mcDto7Iw/k7R+c"
    "Zhsj4HxxH9yIRSPI9fsf/1zPI+WFKhrQqasjVnBYHDUEuaP+mh+fj5QDo5VfuJ7k74uid5w+n25q"
    "aqMTdyOfnT4eoyHInxyoFcwj6TmkHMJggCNJ0F4f1pLwI0Wjyx4UQiUjLMGUH8yXAyMqXwgfTUyE"
    "ID9Sbpz2c6kgPZq5n4dMAqOAT5OeX88Oo9S5EZzY7lajjXuMnk4PlyDKloAaOgywoJWNrR8e0EYj"
    "OnTeHyMQJCOZ7QAf2d0yI8ZKXBwoxCIjsnLYH088F6CGhQ+cuZDkIIViFZ+WKOKj2DQgnL/Jk6JX"
    "wtKfXAcaow5Jz58WQw6jOP8LnyBsTaBVZgkcDr9uIPPDpx97hoIi6T4yH92FKyP1fvQfgWwiIxzr"
    "jR9ONOqm6pakn0bPniBORACfywSao8mn1p+agZGjtVcpnGDb6aPqAMyf4fCVo5Jkd53W0mIgXPjT"
    "H9AxKiOAEmQfZSaJISq09x/B6Qggldr8H0t95yMIuHQcBJjEINvLqxwiP+ijUgH6nwdtf6DYNnaf"
    "n+cMo2gJbpxK/iyjmvAen4arp6PAo7af11DhI5hJRBw2WeomgDPwHxfz2CO6phsfp4sdI/nOTxx7"
    "TnkgRj+xH+dKVCDO7lIdb8Gpo8XcsJ+d4gOjpByWn/KyQqEYtAefB/cYozPnQZyGDGWgxIBSnEYD"
    "0iM1SHAcJB+LI1v6TxyMbPQjRHLVnfZiwCPt7BcfZ3KfI9HQdhyEo9oj7xHdHKa9gaOHBpkcxkcm"
    "o7zrC59eFTejW588n5nQmqOBRBOfV3gvoNUtkZ9hFcUjB61IHADxqSAtN98f5SwEI0nrBhxwutwj"
    "MVDXH1LwQiDdkpgdFb4nIGHB95yAX3Wg1LIXn1lfKqAT9ByfXBRXo9wp75+WMOujpZhZnRs4yqFU"
    "DT8cjmrqIPwqsB1IGuojd590nUZEHSMOah8f0OgdI5G0rB/6fY4jo5uyH0ZVH6a+L0Uc0TO8o2ma"
    "GZ8Uy+qjabeZn85j7KPQiWCcOpOBJuiQpJyfvCGg3Yd/nEC+kCM3tokf8vz5IBOr6R/BOgEmb7mz"
    "H3arEiPUhaScm3QmoTN9Dh9XXzOgek+/ncYHtqMI8bCcVNU8oK8uAZy0hLWjacihn10eMqAsuZKf"
    "xPN2oVuKFZzS71chdDN9nYIqwCDbtBofTWUOILxLlB+CLccjaRxHHBONUSB/bQ4cvFAdoCkE7hwC"
    "mWCgtsd0GrL926NrvhiczhffoP54s5+2TEWgH1a4n2k4u6B8oOycwddIIEBa+B8giQ4gcn1WHMYd"
    "TiAOR/8f+HpJIOpHnx/acwAg+msznY6LTSECCJIfComco3aZV5wxME2gm0m6n+pefaDDXwifqES9"
    "o4ZknJ9NbA2gdoKznUGBzqFX0JWayfBOIL8iIBwiEp0j28qHHNUiZCBsYLUfupYLICZOBhx5ev6h"
    "/PUZnMCisqBmdgodBMPbo/pYZJw/2I2jQ+KjnM6CnqN4bv+cuyfcIHBah5x0YBwh2a/GHJi64iCC"
    "t3AdlqjJIwIVwR83j1EgBmhsHLG/jiOPgA4c4AEGIIn0S50m/dygyoiwHagY7aOZg6ycm28voMVI"
    "p59IcfKgsp6inIfGIaD1FxKaasgLIHlaTBzqUB4g46DMH7dpeSBs2qIfx1N4IGHw7R9jBHgg6c29"
    "HPL8oyDMMwWco2sroEnTVZyds1SgIfULnGLSjqN172GcaMx4oDDpV53sqtCj2nCnHCjTJ6GvTpUc"
    "5rBCofNrhByZD48jdfJLHOyEsSMM0XEcg+OcIz8jlhxmqP2geJ+5nP08BSC2bMucA6uPIS5nSJxa"
    "F5ugdzWMn3FIjKPn75Oc1UjvoDGqf50aDoUgEEfZHGHMMCDzfjsdP9etIHbFchxG2rsgs7OsHL52"
    "tSM50tQd6d4RoWstmpwnDSamZU9InHKxmqM1alKcx+wMoDvbJpzHP9qg20WiHQLkMqFr8jUdCYc7"
    "JvJuSh3k2ZMgpcgkHMIeZSCFzHAcRPbQoRc5Thz65gwgc0zrHadImiFjvaScGqSRISh8+5yRjnIm"
    "OB0fnCQOz6CHS36coVj3oB/Oypws0S+g/71gmsvkcaboPyyd/jjVIPtKnx+pPjsgNwegncz80iE3"
    "VK0cMSsOIC/0HB1VD1CmsLIhGj9Gy6HGd4qcNPlQIacDvpw4TaCg8R5xnQ1lOaEC1gKc0LEMoBqm"
    "1Jzb9xehmDBpHcPH1SHZoBQclMkRIH+PkB8JtQggfaDdHHkAiSC4wikd8L0aIMK7Lx0S8TgmGOQY"
    "nQqLNKAAZtmcRlpgoNCqZZ3/SQ6ggay/nCXe2qAq4UGdHH3tIYSbqJwqso0ghhDyHAzOiiOGJasc"
    "PPl6IZbYGhwFhE+ngsWTHGO29yA+pKccaN+lofXhjh2tu2OhxeIanKcX5KBneLacFm2loMrri5w/"
    "JMugTogEnK7BKabq+4ocqbm1oF22zRwYsBwgSb4rHN6JuCBmt1AcIB4aoYT19x1Mg92g5662HD0C"
    "qKaNp0adw3mqoE2lLZy2VOug4tZsnE3WgKCrfuiddlgLoQdxvpwPj7ognfuTnYO8Fib0qzOaoeEU"
    "IF78RhyM2qgg0QHIHJnX8iDuvtMc/2ecIOFEopxr5WWnFmcanQtf4qDkpe6dyLuDoCtD/5yB3Yag"
    "VNlFnQuyuqF6hrmdtUY6JgSh+51NDK8g1oKmHH1aDiAPlsMdn8f8INwuph1c2IammM6yHKYFICH4"
    "Rg2aAIBGoWh+15ylbqug2CKinG69qKDxLxud4oZZoWSQEJzFNnwm0IbunYMGSyFz93cdQ2KEIeGi"
    "fR31uvAgwgqzHCaONCEbHBYcWaBTIRM3rx24BNYhWlYoHUF7CqE+16acgfxEoXLTcZ1Xvi2g/8Xc"
    "nDni1aCeYZycVxWMoHkqWZ3FvcihqJMjnVydviBRjQ8dNnrkJL4uLx3FxOQgrni4Gv+PMyF2yBAd"
    "ZYhhpm41gZ2HuNmm2zonnbIaECFbEQecClGVIXVb3Zyb05Kgk6bJnMU/v6C5X1+dCD+IpnGZtxgb"
    "swMn9JnZHKUxECGs/f4cnROTIMM7SB2ah00hfloBnehXUKYf7Q2aRI0/plPkqBqLmnOm7+uFnCRQ"
    "iqAw8HGdkJipoNzdlZwYt7yg2/1nmokETyFkAD2aiCDOodkVrByi9AshfweLHOIMnCChv+MdSxRd"
    "Ie8vah3QFBmnZQ4bGv/CU6Fm/T6dF/r3oOVsIp0FX4igREXGHTuYQKE69ymchUuFoN1clp0i8gOh"
    "WW6SneAFMSEh8SkdGpDwIQ5WHB2LNTkh/UXXHGOZgSBf2uQcaG/QpAQA0x1UHPmhMww7GkTZpaH8"
    "4IWckCaAoB1dnJzn2/OgqWKXnP7MeaEZwh2db5+goQubmp1SJR4hfwp4HbSIuyFBEEAdMP0CIaFD"
    "75qh+OggoOc1Ha/E/iFCLM4dhAmEJnNFo5zEUnGhVnOMHcoY5KGUEaicq/eIoBC0fZo973OqP64R"
    "nbfEmCGX3BqYjZCZoXI9AR2DS0YhJHG2HLoQnyDrinkdo+i1IOz8Ih1ccJqma9nZHXOjpiYV9BqY"
    "5CPVJp9Ds5yyHXuhsWl4naR+J6GKvDmd7Wg5oRJZkRqum2MnokZtGg3ovaY4Rgwa5oBbJg1lixzm"
    "MdcgAo4kGpnw6SGQifEdl0gpIbLs1B23Hc2h7hx+mqB0D6HiYaWaItN8obC9Qp24V4+gT+ZjnTg0"
    "h6H5N8mdoNYVocVhrx2VJaIhzZoVHTwiHyF92hodvUIrIeQuLx2rmGwhvpkdHc//oSF4IXkaG+FO"
    "Jm87Tpqbly6hgyXHnUxJBqH5ZmydAQespo3VH50aPy8n9lytnSZVEKaHrQ8aX/55J2nGRRqAERwh"
    "7t5SHXV5bSYC7dCaxffrIe4sFBoS46ohms/6GnYgBKYvRAad4f2YoeIhPZ0oIdqh8h1WncGGDqF7"
    "fsmdfAKyJjAURp027r6hYvH9miuksSFoKDcdTMEuIZJB4R1lPyshBgI3HYsaMSEk5gMdbaP7IZVt"
    "ahoS4tMhmfQ3nfFkrKHXGEud6Cz1oVc7Sp2AwTehkeP1nZBDV6ZYzLSdsTZzpJlPUZqhFOmn3oMw"
    "Gs20+yYs2B4d7N+iIXLGhx0wfMgmhvgYHbRI7SEtluubeq4bJ9CRmZsWmUims4q6mgrTbaa9UOKd"
    "e+XSocdBQJ3S5q6m80+cmhVYnaG9zuAYwBd4Jh3nvh3g+B0hozbNGhJ6MSFgm2AdKkbYJ6s+ixrI"
    "Zqgha0FJmxmbkqEZYg+aF+m1pg6jnxqfNMyhBdBrmq0//6HUvEGdXoQ2oStqoZ2x/U2mWB4OmmrK"
    "oyHYcuAbGdnTIRNG1x0C70ohmL4jHdMbzCE1GngazweAIWUTZxprbpWmA9KVmsUbqqEKuiia+umV"
    "oa7eqJ0cml2mrAFSmnGI/aHVNjKapSh2p3YnUBuyZbYmYO3THYCHqiGlxQkdF0BKIdVdKh3/N7sh"
    "R8QqG5iHkaaO6xaaIpwJpF7zwZ1OeK6h+QSsmmkjsqFdFVKa1DHBocqQGp1zK32mB47wnSN4j6Ef"
    "pOObDCOop79qYBrl78kh149BmrTAGiH4XbEdYRS0IZ/kpB2zLzch9xTlGqmiVaT1VyeaDu4UJwR3"
    "tZqi4gShu0zsnUggVabUbr6dh7MCoe9DIJoQq52hfcvmG+LmiiGQTp0dmGjxIU/YiR3tofshCCAu"
    "Hb+QzSG30qcdIXGjpoTwxZhpx9ch5GweGOYZ8qHAEXiaAf7eoT/I0J1QVu6h80tDmkiKk6GdSmGa"
    "K4bSpuMEApp4XzemIga9HQ3t3yexvU0aXKBZJi4juR2vNo4hly20HY4UpiF7EbMaIxPXppfOphoN"
    "jKCmTIkOmrR7CaatQL+dKy4NoX4trJotPOKnaXvFmhqnP6bHAhMaZNJHJq15rZqwJTcmWJcJm+yf"
    "oyEahoqaXNaVIb9ckx2nMrohTaOvGjjANCeNG5Wa9MB+pg4csp3AQUCmGuuHnfLvv6GS7JCdd9BN"
    "psbX/5opl9am6+ppGyKiWyZukOsYptC5IRiapR0bqIIhEGqmHaqiQSaiQFIalbhpJhWT6RpPFFEn"
    "FEDyGkRdsKadBwcbW3wtprgOiZ2jEfmhWhn4mtG88yddUlya+IdLp+KiDZrnpKAngOkmms5ZQyZc"
    "QEkaSzejIdgcdRrLkp0h7qBOGpq+5ScefuIYpaJmp9I0sphEVAamFMuQnX+aXKbS2oaalmtbph80"
    "ZZpd7mqmtqINmucydqY8krsa/JUnJ755XRr5K6IhcBilHYp87SaX2yMaBu/JIYVKGBqWvTcmLyrx"
    "mpAvRafk9huaAEXGpkOmmp06gjqmyuRVmufY/6a2egaY2UKgoTigTpoXBiimLnqWmnrXbifSGpUd"
    "UC87Jl6fDxqwqp0hW0+OHXkqzCZPi1caCQpSJjOuEhvKKd4mGvyVGl+1HKYoL0aa1eEyph13KZoo"
    "T3Wm6YFMmtF1V6bdW9Cah4Bjp5VkXhtnjNwk2NmimjTtkyYqrJgd6ixQJuXViR1wgAQms6HmmDyA"
    "HqTdqDsaU6gFpsNoXxu+EJknpAidnctfKqaI4jmaYEGCodYiQpqSM52mfGqfnYheQqaLjfUa1cNq"
    "J6nRdxv8YGUnQaRimTTd1ibjrE8aMZQRJp0yShqMH4QhrkwsGsZHxqaaQc2bxmqMprFE3RhoeA+m"
    "JUumnS8pECROqxmawgrlp/S9LJrvnJKmsuy7GsXysCfuFhQat3JqJ/iu1Bqnmlgmap9fGmh1ESbo"
    "yY0aqyxXJqTJVRvy8wcmmemLmkJNvqaKm/SaBZxypns835qzPtOm2PJomtnZyqbGhG+YiRYnpxeY"
    "Nps68LgnI0uEmolLHSbsTZsaV9s8JpO+8BqOki4mzoY0GpCuTyYmHSEa8M1vJ6Vb3Bo4LLqmm6ev"
    "mkSu+KZPJTebOF9op2V1Sppusr6mWUiymrviW6Y4SgkYHPD/psWQ8Bo0lN0mtZUtG857ACfNTKca"
    "8iEBJnwZ4xpPMtkmiR6VGwCisCZlxH8YhMPHppKciZpQW9Om1DVEmvKoBqbwmPuaKurrprWRPZgg"
    "vH2nsN9yGKlNYCRlbeAaUd/ZJk0MDhrFGlgm7SGuGiqV8SbdK8IaDgEEJt4aDhrWvj0nEE8bm6bM"
    "86c9+U2aNmNbpzHmK5sjFB2mswU5mydamqbgWmsYnvOcpmbp75jXbAinzOXWG1DVWydPzNUaNkmG"
    "JMcUQRsRbi0mlZj6GtHcgSYJUqYafOXRJGjtxptcL1Yn0I95m+mA7ab5E0aaTjgCpl9SrppiyOim"
    "hKAcmmbgeaS6jJiayaXop8Y8+RorQBKn7bFXGAVaBCbAjP8aAOcpJlsxrhoAN+gmPa9UGO+i/ycm"
    "jL0b5wjOp6JPwpr0vtan6ztTmze4xaZKiLaaciavpm7FGZrR/qSkPIqfmgfzuqd47D0bLqrFpyAV"
    "PZgLT/kmFpKMGpoBSicOMSkaweN9J/5LohqJD6Am1FKfGxqNW6Q05WGbh6Z0p/dF6JpSXYKmr8vr"
    "mvfGx6cV/IealJxzp2XhIJuH0QWkQ9+YGkALOCcD2fwaQSHYJvwnhhp/53Mn1BuEGloJtSYO9b4a"
    "ucctJ4/GYBeJCYin+FAXm6QpC6QrZbWbHHGCpgyTnJpZIZGmMWMyGCsWVKcZZD4Z"
)


def load_click_pcm() -> bytes:
    """Return the raw float32 mono PCM bytes of the click sound.

    The data was scrambled at build time so it cannot be loaded by a
    casual inspection of the installed app bundle.
    """
    scrambled = base64.b64decode(_DATA_B64)
    key = _KEY
    klen = len(key)
    return bytes(b ^ key[i % klen] for i, b in enumerate(scrambled))
